[python-1207] Initial solution
CC972/leetcode pull request #10
Opened 2021-04-17 20:29 UTC by CC972

2021-04-17 20:40 UTC, GreenSlime96 requested changes

2021-04-17 20:40 UTC, GreenSlime96 commented on python/solutions/problem_1207_unique_number_of_occurances.py
> +def unique_occurances(arr: List[int]) -> bool:
occurence

2021-04-17 20:40 UTC, GreenSlime96 commented on python/solutions/problem_1207_unique_number_of_occurances.py
> +    unique_values: set[int] = set(arr)
is it lowercase `set` or `Set` from package `typing`?

2021-04-17 20:40 UTC, GreenSlime96 commented on python/solutions/problem_1207_unique_number_of_occurances.py
> +        number_of_occurances[value] = number_of_occurances.get(value, 0) + 1
Do you want to use `collections.Counter` instead? Otherwise, `defaultdict` seems more appropriate for this use case as well.

2021-04-17 20:40 UTC, GreenSlime96 commented on python/solutions/problem_1207_unique_number_of_occurances.py
> +    unique_values: set[int] = set(arr)
You don't need `unique_values` here, when you also have them in `number_of_occurences` (because the keys in a dict are unique).

2021-04-18 14:16 UTC, CC972 commented on python/solutions/problem_1207_unique_number_of_occurances.py
> +def unique_occurances(arr: List[int]) -> bool:
Good spot. Fixed!

2021-04-18 14:17 UTC, CC972 commented on python/solutions/problem_1207_unique_number_of_occurances.py
> +    unique_values: set[int] = set(arr)
Fixed.

2021-04-18 14:17 UTC, CC972 commented on python/solutions/problem_1207_unique_number_of_occurances.py
> +        number_of_occurances[value] = number_of_occurances.get(value, 0) + 1
Yep good point :D

2021-04-18 15:24 UTC, GreenSlime96 approved these changes
Nice solution, well done @CC972 !

2021-04-18 15:41 UTC, merged