[python-0500] implement solution
CC972/leetcode pull request #48
Opened 2021-04-25 21:28 UTC by CC972

2021-04-25 21:36 UTC, GreenSlime96 requested changes

2021-04-25 21:36 UTC, GreenSlime96 commented on python/tests/test_problem_0500_keyboard_row.py
> +def test_find_words_returns_words_which_can_be_typed_using_a_single_keyboard_row(words, expected):
where is the `given // when // then`? ;-)

2021-04-25 21:36 UTC, GreenSlime96 commented on python/solutions/problem_0500_keyboard_row.py
> +        word_lower = set(word.lower())
performance gain of converting to set is very negligible here.

if you use a set, you might as well use set subset checking (i.e `first_row <= word_lower or second_row <= word_lower or third_row <= word_lower`)

2021-04-25 21:40 UTC, GreenSlime96 requested changes

2021-04-25 21:40 UTC, GreenSlime96 commented on python/solutions/problem_0500_keyboard_row.py
> +    first_row = set("qwertyuiop")
you can move this outside the function as it's static

2021-04-25 21:43 UTC, GreenSlime96 requested changes

2021-04-25 21:43 UTC, GreenSlime96 commented on python/solutions/problem_0500_keyboard_row.py
> +        for row in (first_row, second_row, third_row):
if you are using sets of characters of `word_lower`, you can also do something like:

```
KEYBOARD_ROWS = [
    set("qwertyuiop"),
    set("asdfghjkl"),
    set("zxcvbnm")
]

if any(row <= word_lower for row in KEYBOARD_ROWS):
    acceptable_words.append(word)
```

Also, if you store capital letters inside the rows as well, you don't need to make passes to lowercase. However, this is a _micro_-optimisation you can ignore as converting to set can be quite expensive.

2021-04-25 22:50 UTC, CC972 commented on python/solutions/problem_0500_keyboard_row.py
> +        word_lower = set(word.lower())
Agreed that converting to a set is probably just a micro-optimisation. Also I think for subset checking it should be `word_lower <= first_row`, etc.

2021-04-25 22:55 UTC, CC972 commented on python/solutions/problem_0500_keyboard_row.py
> +        for row in (first_row, second_row, third_row):
Good idea as this eliminates the nested for loop :)

2021-04-26 18:03 UTC, GreenSlime96 approved these changes

2021-04-26 21:28 UTC, merged