[python-0326] Implement solution
CC972/leetcode pull request #57
Opened 2021-05-11 18:32 UTC by CC972

Tried to generalise problem to work with any positive integer base using a function factory...

2021-05-11 18:37 UTC, CC972 commented on python/tests/test_problem_0326_power_of_three.py
> +def power_of_three():
Ideally I want to have this setup fixture inside each test class instead (as can be done using unittest). Any suggestions on how to do this?

2021-05-11 18:54 UTC, GreenSlime96 requested changes

2021-05-11 19:06 UTC, CC972 commented on python/tests/test_problem_0326_power_of_three.py
> +    def setup(self, power_of_three):
That's great! Works inside the class now.

2021-05-11 19:07 UTC, CC972 commented on python/solutions/problem_0326_power_of_three.py
> +def is_power_of(base: int) -> Callable:
Ah nice I didn't know you could type hint the arguments and return type too :D

2021-05-14 17:18 UTC, GreenSlime96 requested changes

2021-05-14 19:02 UTC, GreenSlime96 approved these changes
Well done Chiguana

2021-05-14 19:02 UTC, merged